server:
  port: 9091
spring:
    # jpa配置
  jpa:
    hibernate:
      ddl-auto: none #update自动生成数据库表 none无变化
      database: mysql
    show-sql: true #是否显示sql
  #数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    #添加数据库连接池的信息
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10




rocketmq:
  #rocketmq消息端口
  name-server: localhost:9876
  #rocketmq发送组
  producer:
    group: group1
